import { describe, test, expect } from "bun:test";
import { readFileSync } from "fs";
import { join } from "path";

const skillMd = readFileSync(join(import.meta.dir, "SKILL.md"), "utf8");
const planningMd = readFileSync(
	join(import.meta.dir, "references/planning.md"),
	"utf8",
);
const completionGateMd = readFileSync(
	join(import.meta.dir, "references/completion-gate.md"),
	"utf8",
);
// Union of body + both references — the behavior-preservation surface ported
// from goal's SKILL.test.ts. A required phrase must survive SOMEWHERE in this
// union; which file it lives in is a routing detail, not a contract.
const combined = skillMd + planningMd + completionGateMd;

// ---------------------------------------------------------------------------
// Prose-contract test for skills/ultragoal/SKILL.md.
//
// ultragoal is a structural copy of goal (skills/goal/SKILL.md) that changes
// exactly two axes: (1) the execution loop dispatches stories to sisyphus one
// at a time, sequentially, gated by a per-story APPROVE verdict before
// advancing; (2) decomposition is auto-generated by the orchestrator and
// bulk-approved by the user in one call (`confirm-all-stories`) instead of
// goal's per-story `confirm-story` dialogue. The completion gate itself is
// REUSED from goal, not redesigned: per-story self-attested verdicts gate
// mid-loop advance, and the independent code-review lane still runs exactly
// once — now explicitly at the final story, over the accumulated diff.
// ---------------------------------------------------------------------------

describe("ported from goal: read-discipline (SKILL.md points at extracted references)", () => {
	test("SKILL.md instructs reading references/planning.md before planning/story subcommands", () => {
		expect(skillMd).toContain(
			"You MUST read `references/planning.md` first",
		);
	});

	test("SKILL.md instructs reading references/completion-gate.md before the completion sequence", () => {
		expect(skillMd).toContain(
			"You MUST read `references/completion-gate.md` first",
		);
	});
});

describe("ported from goal: Six Slots and Story Definition detail lives in references/planning.md", () => {
	test("slot-definition detail is absent from SKILL.md body", () => {
		expect(skillMd).not.toContain(
			"**outcome** (`--outcome`) — what is true when the objective is reached",
		);
	});

	test("slot-definition detail is present in references/planning.md", () => {
		expect(planningMd).toContain(
			"**outcome** (`--outcome`) — what is true when the objective is reached",
		);
	});

	test("set-stories --single detail (ultragoal-state.ts) is absent from SKILL.md body", () => {
		expect(skillMd).not.toContain(
			"bun ${CLAUDE_SKILL_DIR}/scripts/ultragoal-state.ts set-stories --single",
		);
	});

	test("set-stories --single detail (ultragoal-state.ts) is present in references/planning.md", () => {
		expect(planningMd).toContain(
			"bun ${CLAUDE_SKILL_DIR}/scripts/ultragoal-state.ts set-stories --single",
		);
	});

	test("Mid-flight Story Mutations subcommand detail is absent from SKILL.md body", () => {
		expect(skillMd).not.toContain(
			"**`add-story --json '<story>'`** — appends one new story with status `unconfirmed`",
		);
	});

	test("Mid-flight Story Mutations subcommand detail is present in references/planning.md", () => {
		expect(planningMd).toContain(
			"**`add-story --json '<story>'`** — appends one new story with status `unconfirmed`",
		);
	});
});

describe("ported from goal: Completion Gate detail lives in references/completion-gate.md", () => {
	test("evidence rubric detail is absent from SKILL.md body", () => {
		expect(skillMd).not.toContain(
			"**prompt-to-artifact mapping** — map every explicit requirement, numbered item, named file, command, test, gate, and deliverable in the verification surface to concrete evidence",
		);
	});

	test("evidence rubric detail is present in references/completion-gate.md", () => {
		expect(completionGateMd).toContain(
			"**prompt-to-artifact mapping** — map every explicit requirement, numbered item, named file, command, test, gate, and deliverable in the verification surface to concrete evidence",
		);
	});

	test("code-review artifact schema detail is absent from SKILL.md body", () => {
		expect(skillMd).not.toContain('"status": "COMPLETE|INCONCLUSIVE"');
	});

	test("code-review artifact schema detail is present in references/completion-gate.md", () => {
		expect(completionGateMd).toContain('"status": "COMPLETE|INCONCLUSIVE"');
	});

	test("Blocked-stop B1/B2 detail is absent from SKILL.md body", () => {
		expect(skillMd).not.toContain(
			"**B1** — the objective self-check names NO actionable incomplete work item",
		);
	});

	test("Blocked-stop B1/B2 detail is present in references/completion-gate.md", () => {
		expect(completionGateMd).toContain(
			"**B1** — the objective self-check names NO actionable incomplete work item",
		);
	});
});

describe("ported from goal (regression): required phrases survive somewhere in body+references", () => {
	test("all six slot names are named somewhere in the union", () => {
		expect(combined).toContain("**outcome** (`--outcome`)");
		expect(combined).toContain(
			"**verification-surface** (`--verification-surface`)",
		);
		expect(combined).toContain("**constraints** (`--constraints`)");
		expect(combined).toContain("**boundaries** (`--boundaries`)");
		expect(combined).toContain(
			"**iteration-policy** → `max_iterations` (`--max-iterations <n>`)",
		);
		expect(combined).toContain("**blocked-stop** (`--blocked-stop <text>`)");
	});

	test("the never-false-complete invariant survives in the union", () => {
		expect(combined).toContain(
			"the never-false-complete invariant in `request-complete` structurally requires `objective_verdict=APPROVE`",
		);
	});

	test("INCONCLUSIVE status routing survives in the union", () => {
		expect(combined).toContain(
			'`status === "INCONCLUSIVE"` blocks regardless of findings',
		);
		expect(combined).toContain(
			"An `INCONCLUSIVE` status routes to a **reviewer-only re-run** instead — re-dispatch a fresh **code-reviewer** over the same diff, NOT sisyphus",
		);
	});
});

// ---------------------------------------------------------------------------
// Distinctive ultragoal contracts — the two axes that differ from goal, plus
// the invariants the SSOT spec (deep-interview/ultragoal-skill.md) requires
// to survive the restructure: sisyphus stays the executor, single-story
// degrades to goal, and the code-review lane stays final-only.
// ---------------------------------------------------------------------------

describe("axis 1: per-story sequential dispatch with an APPROVE advance gate", () => {
	test("SKILL.md states stories dispatch to sisyphus one at a time, sequentially", () => {
		expect(skillMd).toMatch(
			/dispatches? .*confirmed stories? to sisyphus.*\*\*one (story )?at a time,? (in sequence|sequentially)\*\*/is,
		);
	});

	test("SKILL.md states the next story is never dispatched before the current one's per-story verdict is APPROVE", () => {
		expect(skillMd).toContain(
			"the next story is never dispatched until the current story's per-story verdict is `APPROVE`",
		);
	});

	test("SKILL.md's Execution Dispatch loop names an explicit advance-only-on-APPROVE rule", () => {
		expect(skillMd).toContain("**Advance only on APPROVE.**");
	});

	test("SKILL.md no longer dispatches the whole Story set in one sisyphus call (goal's shape)", () => {
		expect(skillMd).not.toContain(
			'then dispatches execution to sisyphus: `Skill(skill: "sisyphus")` with the adopted Story set.',
		);
	});
});

describe("axis 2: auto-generated decomposition + bulk approval via confirm-all-stories", () => {
	test("SKILL.md or planning.md documents confirm-all-stories as the bulk-approve affordance", () => {
		expect(combined).toContain("confirm-all-stories");
		expect(combined).toContain(
			"bun ${CLAUDE_SKILL_DIR}/scripts/ultragoal-state.ts confirm-all-stories",
		);
	});

	test("planning.md frames decomposition as auto-generate, not a per-story confirm dialogue", () => {
		expect(planningMd).toContain("auto-generate");
		expect(planningMd).toContain(
			"replacing goal's per-story `confirm-story` dialogue",
		);
	});

	test("planning.md documents reorder-stories as a planning-time steering mutation", () => {
		expect(planningMd).toContain("reorder-stories");
		expect(planningMd).toContain("--order <id1,id2,...>");
	});
});

describe("gate cost model: per-story self-attested verdict mid-loop, code-review final-only", () => {
	test("completion-gate.md states the code-review lane runs once, at the final story, over the accumulated diff", () => {
		expect(completionGateMd).toContain(
			"runs once, at the final story — not per story",
		);
	});

	test("SKILL.md states middle stories get a self-attested per-story verdict with no per-story code-review", () => {
		expect(skillMd).toContain(
			"Middle stories get a **lightweight, self-attested per-story verdict**",
		);
		expect(skillMd).toContain("no code-review runs per story");
	});

	test("artifact prefixes are ultragoal's own namespace", () => {
		expect(combined).toContain("ultragoal-verdict-{sid}.json");
		expect(combined).toContain("ultragoal-codereview-{sid}.json");
	});

	test("no bare (non-ultra-prefixed) goal-verdict/goal-codereview artifact reference remains", () => {
		// "ultragoal-verdict-{sid}.json" naturally CONTAINS "goal-verdict-{sid}.json"
		// as a substring, so a bare not.toContain on that string is always false —
		// strip every ultragoal-prefixed occurrence first, then check what's left.
		const withoutUltraPrefixed = combined
			.split("ultragoal-verdict-{sid}.json")
			.join("")
			.split("ultragoal-codereview-{sid}.json")
			.join("");
		expect(withoutUltraPrefixed).not.toContain("goal-verdict-{sid}.json");
		expect(withoutUltraPrefixed).not.toContain("goal-codereview-{sid}.json");
	});
});

describe("single-story degrade: ultragoal collapses to goal's single-gate behavior", () => {
	test("SKILL.md states a single-story objective degrades to goal's behavior", () => {
		expect(skillMd).toContain("**Single-story degrade.**");
		expect(skillMd).toContain("ultragoal degrades to goal's behavior");
	});
});

describe("invariant: sisyphus stays the executor, no runtime goal call", () => {
	test("SKILL.md dispatches execution via Skill(skill: \"sisyphus\")", () => {
		expect(skillMd).toContain('Skill(skill: "sisyphus")');
	});

	test("SKILL.md never invokes Skill(skill: \"goal\") at runtime", () => {
		expect(skillMd).not.toContain('Skill(skill: "goal")');
	});

	test("SKILL.md states explicitly that ultragoal never invokes goal at runtime", () => {
		expect(skillMd).toContain(
			"ultragoal never invokes the goal skill at runtime",
		);
	});
});

describe("identity: frontmatter and state-namespace point at ultragoal, not goal", () => {
	test("frontmatter name is ultragoal", () => {
		expect(skillMd).toMatch(/^name: ultragoal$/m);
	});

	test("State CLI points at ultragoal-state.ts, not goal-state.ts", () => {
		expect(skillMd).toContain(
			"bun ${CLAUDE_SKILL_DIR}/scripts/ultragoal-state.ts <subcommand> [options]",
		);
		// "ultragoal-state.ts" naturally contains "goal-state.ts" as a substring, so a
		// bare not.toContain would always fail here — a negative lookbehind excludes
		// the ultra-prefixed occurrences and checks only for a BARE goal-state.ts.
		expect(skillMd).not.toMatch(/(?<!ultra)goal-state\.ts/);
	});
});

// ---------------------------------------------------------------------------
// Stop-hook arming gap: the persistent-mode Stop hook only refuses to stop
// while `phase === "pursuing"`. The Execution Dispatch numbered list must
// carry the `set --phase pursuing` transition BEFORE the first sisyphus
// dispatch step, or an agent that follows the list verbatim leaves the first
// story's entire execution window unarmed.
// ---------------------------------------------------------------------------

describe("Stop-hook arming gap: pursuing transition precedes first dispatch", () => {
	// Scoped to the numbered list itself, not the whole Execution Dispatch
	// section — the section also contains the "### Phase transitions"
	// subsection, which carried a `set --phase pursuing` mention before the
	// "ultragoal phase 전환을 첫 sisyphus 디스패치 전으로 승격" commit (at the
	// wrong point in the loop; SKILL.md:99 now correctly reads "Before the
	// first sisyphus dispatch"). Reproduced against the pre-change SKILL.md
	// (worktree at commit cc219293) with the scope widened to the whole
	// section: the containment assertion (`toContain('set --phase
	// pursuing')`) would have passed spuriously on that pre-existing mention.
	// The ordering assertion would NOT have — the mention lives in
	// "### Phase transitions", which sits AFTER the "Dispatch ONLY that one
	// story" instruction, so it still fails under the widened scope at base.
	// The containment assertion alone is enough to justify keeping the scope
	// on the numbered list: the step being absent from the numbered list an
	// agent reads to drive the dispatch loop is what the widened scope would
	// hide.
	const numberedList = skillMd.slice(
		skillMd.indexOf("## Execution Dispatch"),
		skillMd.indexOf("### Phase transitions"),
	);

	test("the Execution Dispatch numbered list carries a set --phase pursuing step", () => {
		expect(numberedList).toContain("set --phase pursuing");
	});

	test("the pursuing transition is positioned before the sisyphus dispatch instruction", () => {
		// Anchored to "Dispatch ONLY that one story" (step 3's actual dispatch
		// instruction), not a bare `Skill(skill: "sisyphus")` lookup — that
		// string's FIRST occurrence in numberedList is step 1's own
		// self-referential sentence ("This must run BEFORE the first
		// `Skill(skill: "sisyphus")` call below"), not step 3's dispatch. A
		// bare-string anchor would still pass if step 3's actual dispatch
		// instruction were deleted and only step 1's self-reference remained.
		expect(numberedList.indexOf("set --phase pursuing")).toBeGreaterThan(-1);
		expect(
			numberedList.indexOf("Dispatch ONLY that one story"),
		).toBeGreaterThan(-1);
		expect(numberedList.indexOf("set --phase pursuing")).toBeLessThan(
			numberedList.indexOf("Dispatch ONLY that one story"),
		);
	});

	test("the stale 'After the first sisyphus dispatch' ordering no longer appears", () => {
		expect(skillMd).not.toContain("After the first sisyphus dispatch");
	});

	test("the narrative arrow order reads set --phase pursuing before dispatch story #1", () => {
		// Scoped to the "Initial path" narrative sentence specifically — a bare
		// whole-file indexOf comparison would have passed spuriously even
		// before the "ultragoal phase 전환을 첫 sisyphus 디스패치 전으로 승격"
		// commit's fix, since the Phase-transitions code
		// block's `set --phase pursuing` mention sits earlier in the file than
		// the narrative's "dispatch story #1", regardless of the narrative
		// sentence's own arrow order — which, at that point, was reversed (now
		// corrected to `set --phase pursuing` → `dispatch story #1`,
		// SKILL.md:104).
		const initialPath = skillMd.slice(
			skillMd.indexOf("Initial path:"),
			skillMd.indexOf("Re-plan loop-back:"),
		);
		expect(initialPath.indexOf("dispatch story #1")).toBeGreaterThan(-1);
		expect(initialPath.indexOf("set --phase pursuing")).toBeGreaterThan(-1);
		expect(initialPath.indexOf("set --phase pursuing")).toBeLessThan(
			initialPath.indexOf("dispatch story #1"),
		);
	});

	test("the Re-plan loop-back narrative reads confirm-all-stories before set --phase pursuing before dispatch", () => {
		// Sliced from "Re-plan loop-back:" through the next section boundary
		// ("## Completion Gate") — reading SKILL.md directly (line 104)
		// confirms this slice contains exactly one Re-plan loop-back sentence
		// and stops before the next section, so it does not repeat the scope
		// trap the four tests above guard against (a slice wide enough to let
		// an incidentally-ordered mention elsewhere in the file pass
		// spuriously).
		const replanLoopBack = skillMd.slice(
			skillMd.indexOf("Re-plan loop-back:"),
			skillMd.indexOf("## Completion Gate"),
		);
		expect(replanLoopBack.indexOf("confirm-all-stories")).toBeGreaterThan(-1);
		expect(replanLoopBack.indexOf("set --phase pursuing")).toBeGreaterThan(
			-1,
		);
		expect(
			replanLoopBack.indexOf("dispatch the fresh sisyphus call"),
		).toBeGreaterThan(-1);
		expect(replanLoopBack.indexOf("confirm-all-stories")).toBeLessThan(
			replanLoopBack.indexOf("set --phase pursuing"),
		);
		expect(replanLoopBack.indexOf("set --phase pursuing")).toBeLessThan(
			replanLoopBack.indexOf("dispatch the fresh sisyphus call"),
		);
	});
});
